#!/bin/bash
# Manual transfer instructions for VPS
# VPS: root@45.155.69.163
# Password: wvds2ZAzxk3H
# Path: /root/ModelNetBeta

echo "===================================="
echo "  Manual Database Transfer to VPS"
echo "===================================="
echo ""
echo "VPS Details:"
echo "  Host: 45.155.69.163"
echo "  User: root"
echo "  Path: /root/ModelNetBeta"
echo ""
echo "Database export ready:"
echo "  File: database_exports/ollama_scanner_export_20251009_112844.sql"
echo "  Size: 264K"
echo "  Contains: 1,340 endpoints, 161 verified, 127 honeypots, 1,415 models"
echo ""
echo "===================================="
echo "Step 1: Transfer the export file"
echo "===================================="
echo ""
echo "Run this command (you'll be prompted for password):"
echo ""
echo "scp database_exports/ollama_scanner_export_20251009_112844.sql root@45.155.69.163:/root/ModelNetBeta/"
echo ""
echo "Password: wvds2ZAzxk3H"
echo ""
read -p "Press Enter after you've transferred the file..."
echo ""
echo "===================================="
echo "Step 2: SSH to VPS and import"
echo "===================================="
echo ""
echo "Run these commands:"
echo ""
echo "ssh root@45.155.69.163"
echo "# Password: wvds2ZAzxk3H"
echo ""
echo "cd /root/ModelNetBeta"
echo "./import_database.sh ollama_scanner_export_20251009_112844.sql"
echo ""
echo "===================================="
echo "Or use this one-liner on VPS:"
echo "===================================="
echo ""
echo "ssh root@45.155.69.163 'cd /root/ModelNetBeta && ./import_database.sh ollama_scanner_export_20251009_112844.sql'"
echo ""

